TravelTrip/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelTrip.Classes;

namespace TravelTrip.Controllers
{
    public class AdminController : Controller
    {
   
        // GET: Admin
        Context c = new Context();
        [Authorize]
        public ActionResult Index()
        {
            var data = c.Blogs.ToList();
            return View(data);
        }
        public ActionResult AddBlog()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddBlog(Blog model)
        {
            c.Blogs.Add(model);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult BlogRemove(int id)
        {

            var data = c.Blogs.Find(id);
            c.Blogs.Remove(data);
            c.SaveChanges();

            return RedirectToAction("Index");
        }
        public ActionResult GetBlog(int id)
        {
            var bl = c.Blogs.Find(id);
            return View("GetBlog",bl);
        }
        [HttpPost]
        public ActionResult ModifiedBlog(Blog model)
        {
            var data = c.Blogs.Find(model.BlogId);
            data.BlogId = model.BlogId;
            data.Description = model.Description;
            data.Title = model.Title;
            data.BlogImage = model.BlogImage;
            data.Date = model.Date;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult CommentList()
        {
            var comments=c.Comments.ToList();
            return View(comments);
        }
        public ActionResult CommentRemove(int id)
        {
            var data = c.Comments.Find(id);
            c.Comments.Remove(data);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult GetComment(int id)
        {
            var data = c.Comments.Find(id);
            return View("GetComment", data);
        }
        [HttpPost]
        public ActionResult CommentModify(Comment comment)
        {
            var result = c.Comments.Find(comment.CommentId);


            result.CommentId = comment.CommentId;
            result.UserName = comment.UserName;
            result.Mail = comment.Mail;
            result.Comments = comment.Comments;
            
            c.SaveChanges();
            return RedirectToAction("CommentList");
        }
    }
}

TravelTrip/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelTrip.Classes;

namespace TravelTrip.Controllers
{
    public class BlogController : Controller
    {
        // GET: Blog
        Context c = new Context();
        BlogComment bc = new BlogComment();

        public ActionResult Index()
        {
            bc.BlogValue = c.Blogs.ToList();
            bc.Value3 = c.Blogs.OrderByDescending(x=>x.BlogId).Take(3).ToList();
            return View(bc);
        }
        public ActionResult BlogDetail(int id)
        {
            bc.BlogValue = c.Blogs.Where(x => x.BlogId == id).ToList();
            bc.CommentValue = c.Comments.Where(x => x.BlogId == id).ToList();
            return View(bc);
        }

        public PartialViewResult Comment(int id)
        {
            ViewBag.value = id;
            return PartialView();
        }
        [HttpPost]
       public PartialViewResult Comment(Comment model)
        {
            c.Comments.Add(model);
            c.SaveChanges();
            return PartialView();
        }
    }
}

TravelTrip/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelTrip.Classes;

namespace TravelTrip.Controllers
{
    public class DefaultController : Controller
    {
        // GET: Default

        Context c = new Context();
        public ActionResult Index()
        {

            var values = c.Blogs.Take(5).ToList();
            return View(values);
        }
        public ActionResult About()
        {
            var data = c.Abouts.ToList();
            return View(data);
        }

        public PartialViewResult Partial()
        {
            var values = c.Blogs.OrderByDescending(x => x.BlogId).Take(2).ToList();
            return PartialView(values);
        }
            public PartialViewResult Partial2()
        {
            var value = c.Blogs.Where(x => x.BlogId == 1).ToList();
            return PartialView(value);
        }
        public PartialViewResult Partial3()
        {
            var value = c.Blogs.ToList();
            return PartialView(value);
        }
        public PartialViewResult Partial4()
        {
            var value = c.Blogs.Take(3).ToList();
            return PartialView(value);
        }
        public PartialViewResult Partial5()
        {
            var value = c.Blogs.Take(3).OrderByDescending(x=>x.BlogId).ToList();
            return PartialView(value);
        }
    }
}

TravelTrip/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using TravelTrip.Classes;

namespace TravelTrip.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        Context c = new Context();
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(Admin admin)
        {
            var data = c.Admins.FirstOrDefault(x => x.User == admin.User && x.Password == admin.Password);
            if (data!=null)
            {
                FormsAuthentication.SetAuthCookie(data.User,false);
                Session["User"] = data.User.ToString();
                return RedirectToAction("Index","Admin");
            }
            else
            {
                return View();
            }
           
        }
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login","Login");
        }
    }
}

TravelTrip/Views/Admin/AddBlog.cshtml
@model TravelTrip.Classes.Blog
@{
    ViewBag.Title = "AddBlog";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Blog Ekleme Sayfası</h2>
<br />
<form class="form-group" method="post">

    @Html.Label("Başlık")
    @Html.TextBoxFor(x => x.Title, new { @class = "form-control" })
    <br />
    @Html.Label("İçerik")
    @Html.TextAreaFor(x => x.Description, new { @class = "form-control" })
    <br />
    @Html.Label("Tarih")
    @Html.TextBoxFor(x => x.Date, new { @class = "form-control" })

    <br />
    @Html.Label("Resim")
    @Html.TextBoxFor(x => x.BlogImage, new { @class = "form-control" })
<br />
    <button class="btn btn-primary">Blog Ekle</button>
</form>

TravelTrip/Views/Admin/CommentList.cshtml
@using TravelTrip.Classes
@model List<Comment>
@{
    ViewBag.Title = "CommentList";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Comment List</h2>

<table class="table table-responsive">

    <tr>
        <th>ID</th>
        <th>Kullanıcı Adı</th>
        <th>Mail</th>
        <th>Yorum</th>
        <th>Blog</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>

    @foreach (var x in Model)
    {
<tr>
    <td>@x.CommentId</td>
    <td>@x.UserName</td>
    <td>@x.Mail</td>
    <td>@x.Comments</td>
    <td>@x.Blog.Title</td>
    <td><a class="btn btn-danger" href="/Admin/CommentRemove/@x.CommentId">Sil</a></td>
    <td><a  class="btn btn-warning" href="/Admin/GetComment/@x.CommentId">Güncelle</a></td>
</tr>
    }


</table>

TravelTrip/Views/Admin/GetBlog.cshtml
@model TravelTrip.Classes.Blog
@{
    ViewBag.Title = "GetBlog";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Blog Güncelle</h2>
<br />
@using (Html.BeginForm("ModifiedBlog", "Admin", FormMethod.Post))
{
    @Html.Label("ID")
    @Html.TextBoxFor(x => x.BlogId, new { @class = "form-control",@readonly="readonly" })
    <br />
    @Html.Label("Başlık")
    @Html.TextBoxFor(x => x.Title, new { @class = "form-control" })
    <br />
    @Html.Label("İçerik")
    @Html.TextAreaFor(x => x.Description, 15, 1, new { @class = "form-control" })
    <br />
    @Html.Label("Tarih")
    @Html.TextBoxFor(x => x.Date, new { @class = "form-control" })

    <br />
    @Html.Label("Resim")
    @Html.TextBoxFor(x => x.BlogImage, new { @class = "form-control" })
    <br />
    <button class="btn btn-primary">Blog Güncelle</button>
}

TravelTrip/Views/Admin/GetComment.cshtml
@model TravelTrip.Classes.Comment
@{
    ViewBag.Title = "GetComment";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("CommentModify", "Admin", FormMethod.Post))
{
    @Html.Label("ID")
    @Html.TextBoxFor(x => x.CommentId, new { @class = "form-control", @readonly = "readonly" })
    <br />
    @Html.Label("Kullanıcı Adı")
    @Html.TextBoxFor(x => x.UserName, new { @class = "form-control" })
    <br />
    @Html.Label("Mail")
    @Html.TextAreaFor(x => x.Mail, new { @class = "form-control" })
    <br />
    @Html.Label("Yorum")
    @Html.TextAreaFor(x => x.Comments, new { @class = "form-control" })

    <br />
  
    <button class="btn btn-primary">Yorum Güncelle</button>
}

TravelTrip/Views/Admin/Index.cshtml
@using  TravelTrip.Classes
@model List<Blog>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Index</h2>

<br />
<table class="table table-bordered">

    <tr>
        <th>ID</th>
        <th>Başlık</th>
        <th>İçerik</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Detaylar</th>
    </tr>
    @foreach (var x in Model)
    {

<tr>
    <td>@x.BlogId</td>
    <td>@x.Title</td>
    <td>@x.Description</td>
    <td><a class="btn btn-danger" href="/Admin/BlogRemove/@x.BlogId">Sil</a></td>
    <td><a class="btn btn-info" href="/Admin/GetBlog/@x.BlogId">Güncelle</a></td>
    <td><a class="btn btn-success" href="/Blog/BlogDetail/@x.BlogId">Detaylar</a></td>

</tr>
    }

    
</table>
<a href="/Admin/AddBlog/" class="btn btn-primary">Blog Ekle</a>

TravelTrip/Views/Blog/BlogDetail.cshtml
@using TravelTrip.Classes
@model BlogComment
@{
    ViewBag.Title = "BlogDetail";
    Layout = "~/Views/Shared/_T.cshtml";
}

<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
    <title>Personal Blog a Blogging Category Flat Bootstarp  Responsive Website Template | Single :: w3layouts</title>
    <link href="~/web2/css/bootstrap.css" rel='stylesheet' type='text/css' />
    <link href="~/web2/css/style.css" rel='stylesheet' type='text/css' />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Personal Blog Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
	Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!----webfonts---->
    <link href='http://fonts.googleapis.com/css?family=Oswald:100,400,300,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,300italic' rel='stylesheet' type='text/css'>
    <!----//webfonts---->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <!--end slider -->
    <!--script-->
    <script type="text/javascript" src="js/move-top.js"></script>
    <script type="text/javascript" src="js/easing.js"></script>
    <!--/script-->
    <script type="text/javascript">
			jQuery(document).ready(function($) {
				$(".scroll").click(function(event){
					event.preventDefault();
					$('html,body').animate({scrollTop:$(this.hash).offset().top},900);
				});
			});
    </script>
    <!---->

</head>
<body>
    <!---header---->
    <div class="header">
     
    </div>
    <!--/header-->
    <div class="single">
        <div class="container">
            <div class="col-md-8 single-main">
                <div class="single-grid">
                    @foreach (var x in Model.BlogValue)
                    {
                        <img src="@x.BlogImage" alt="" style="margin-bottom:20px" />
                        <h2>@x.Title</h2>
                        <p>
                            @x.Description
                        </p>
                    }
                </div>
                @foreach (var y in Model.CommentValue)
                {


                    <ul class="comment-list">
                        <li>
                            <img src="~/web2/images/avatar.png" class="img-responsive" alt="">
                            <div class="desc">
                                <p>@y.UserName: @y.Comments </p>
                            </div>
                            <div class="clearfix"></div>
                        </li>

                    </ul>
                }

                @Html.Action("Comment","Blog")
            </div>

            <div class="col-md-4 side-content">
                <div class="recent">
                    <h3>RECENT POSTS</h3>
                    <ul>
                        <li><a href="#">Aliquam tincidunt mauris</a></li>
                        <li><a href="#">Vestibulum auctor dapibus  lipsum</a></li>
                        <li><a href="#">Nunc dignissim risus consecu</a></li>
                        <li><a href="#">Cras ornare tristiqu</a></li>
                    </ul>
                </div>
                <div class="comments">
                    <h3>RECENT COMMENTS</h3>
                    <ul>
                        <li><a href="#">Amada Doe </a> on <a href="#">Hello World!</a></li>
                        <li><a href="#">Peter Doe </a> on <a href="#"> Photography</a></li>
                        <li><a href="#">Steve Roberts  </a> on <a href="#">HTML5/CSS3</a></li>
                    </ul>
                </div>
                <div class="clearfix"></div>
                
                
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    </body>
</html>
    <!---->

TravelTrip/Views/Blog/Comment.cshtml
@model TravelTrip.Classes.Comment

<div class="content-form">
    <h3>Yorum Yapın..</h3>
    <form method="post">
       
        <input type="hidden" name="BlogId" value="@ViewBag.value" />

        <input type="text" name="UserName" placeholder="Kullanıcı Adı" required />
        <input type="text" name="Mail" placeholder="Email" required />

        <textarea name="Comments" placeholder="Yorum"></textarea>
        <input type="submit" value="Gönder" />
    </form>
</div>

TravelTrip/Views/Blog/Index.cshtml
@using TravelTrip.Classes
@model BlogComment
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_T.cshtml";
}

<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
    <link href="~/web2/css/bootstrap.css" rel='stylesheet' type='text/css' />
    <link href="~/web2/css/style.css" rel='stylesheet' type='text/css' />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Personal Blog Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
	Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!----webfonts---->
    <link href='http://fonts.googleapis.com/css?family=Oswald:100,400,300,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,300italic' rel='stylesheet' type='text/css'>
    <!----//webfonts---->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <!--end slider -->
    <!--script-->
    <script type="text/javascript" src="js/move-top.js"></script>
    <script type="text/javascript" src="js/easing.js"></script>
    <!--/script-->
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            $(".scroll").click(function (event) {
                event.preventDefault();
                $('html,body').animate({ scrollTop: $(this.hash).offset().top }, 900);
            });
        });
    </script>
    <!---->

</head>
<body>
    <!---header---->
    <div class="header">
        <div class="container">

            <!---start-top-nav---->

            <div class="clearfix"></div>

        </div>
    </div>
    <!--/header-->
    <div class="single">
        <div class="container">
            <div class="col-md-8 single-main">
                @foreach (var x in Model.BlogValue)
                {
                    <div class="single-grid">
                        <img src="@x.BlogImage" alt="" style="margin-bottom:20px"/>
                        <a href="/Blog/BlogDetail/@x.BlogId">@x.Title</a>
                        <p>
                            @x.Description
                        </p>
                    </div>
                  <br />
                }

            </div>

            <div class="col-md-4 side-content">
                <div class="recent">
                    <h3>Son Bloglar</h3>
                    @foreach (var x in Model.Value3)
                    {

                        <ul>
                            <li><a href="/Blog/BlogDetail/@x.BlogId">@x.Title</a></li>

                        </ul>
                    }

                </div>
                <div class="comments">
                    <h3>Son Yorumlar</h3>
                    <ul>
                        <li><a href="#">Amada Doe </a> on <a href="#">Hello World!</a></li>
                        <li><a href="#">Peter Doe </a> on <a href="#"> Photography</a></li>
                        <li><a href="#">Steve Roberts  </a> on <a href="#">HTML5/CSS3</a></li>
                    </ul>
                </div>


                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</body>
<!---->
</html>

TravelTrip/Views/Default/About.cshtml
@model List<TravelTrip.Classes.About>
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/_T.cshtml";
}

<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
    <div class="content">
        <div class="wrap">
            <div class="about">
                <h3>About</h3>

                @foreach (var x in Model)
                {
                    <img src="@x.ImageUrl" alt="" />
                    
                    <p>  @x.Description</p>

                }


            </div>
        </div>
    </div>

TravelTrip/Views/Default/Index.cshtml
@using TravelTrip.Classes
@model List<Blog>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_T.cshtml";
}

<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>

<body>
    
    
    <div class="header-banner">
        <div class="wrap">
            <div class="banner">
                <div class="indent">
                    <h2 class="indent-left margin-bot">Plan the Easy Trip</h2>
                    <div class="banner-left">
                        <div class="con-text">
                            <div class="grid1-img">
                                <img src="~/web/images/glass.png" alt="">
                            </div>
                            <div class="grid1-desc">
                                <p>Restaurantlar</p>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="con-text">
                            <div class="grid1-img">
                                <img src="~/web/images/flight.png" alt="">
                            </div>
                            <div class="grid1-desc">
                                <p>Uçuşlar</p>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="con-text">
                            <div class="grid1-img">
                                <img src="~/web/images/group.png" alt="">
                            </div>
                            <div class="grid1-desc">
                                <p>Yapılacak Şeyler</p>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="con-text">
                            <div class="grid1-img">
                                <img src="~/web/images/key.png" alt="">
                            </div>
                            <div class="grid1-desc">
                                <p>Araba Kiralama</p>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="header_bottom_right_images">

                        <div class="slider"style="width:650px;height:350px;">
                            <ul class="rslides" id="slider1">
                                @foreach (var x in Model)
                                {
                                    <li><img src="@x.BlogImage" alt=""></li>

                                }

                            </ul>
                        </div>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
    <div class"content">
        <div class="wrap">
            <div class="wrapper">
                <div class="con-top">
                    <h3>Welcome to vacation&travel blog!</h3>
                    <p>MVC5 Dinamik web sitesi.</p>
                </div>
                @Html.Action("Partial","Default")
                <div class="grids">
                    <div class="box1">
                        @Html.Action("Partial3","Default")
                        @Html.Action("Partial4","Default")
                        <div class="clear"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
</body>
</html>

TravelTrip/Views/Default/Partial.cshtml
@using TravelTrip.Classes
@model List<Blog>
    <div class="con-bot">
        @foreach (var x in Model)
        {
            <div class="left">
                <div class="bot-left">
                    <img src="@x.BlogImage" alt="" />
                </div>
                <div class="left-text">
                    <h4>@x.Title</h4>
                    <span class="doller">@x.Date.ToString("dd.MM.yyyy")</span>
                    <p>@x.Description.Substring(0,80)</p>
                    <p><a href="/Blog/BlogDetail/@x.BlogId"><span class="read">Devamını Oku... >></span></a></p>
                </div>
            </div>
        }
        </div>
@Html.Action("Partial2","Default")
   

TravelTrip/Views/Default/Partial2.cshtml
@using TravelTrip.Classes
@model List<Blog>
@foreach (var x in Model)
{

<div class="right">
            <div class="bot-left">
                <img src="@x.BlogImage" alt="" />
            </div>
            <div class="left-text">

                <h4>@x.Title</h4>
                <span class="doller">@x.Date.ToString("dd.MM.yyyy")</span>
                <p>@x.Description.Substring(0,80)...
                
                </p>
                <p><a href="/Blog/BlogDetail/@x.BlogId"><span class="read">Devamını Oku... >></span></a></p>
            </div>
        </div>
        <div class="clear"></div>
    
        
}

TravelTrip/Views/Default/Partial3.cshtml
@using TravelTrip.Classes
@model List<Blog>
    <div class="padding">
        <h4>This Week's Top 10</h4>
        
        <ul class="list list-pad">
            @{ 
                int i = 0;
            }
            @foreach (var x in Model)
            {
                <li class="list-bg"><span>@{i++;}@i.</span><a href="/Blog/BlogDetail/@x.BlogId">@x.Title</a></li>

            }

        </ul>
        <a href="/Blog/Index/" class="link1">Tüm Blogları Gör.</a>
    </div>

TravelTrip/Views/Default/Partial4.cshtml
@using TravelTrip.Classes
@model List<Blog>
    <div class="padding1">
        <h4>Our Best Places</h4>
        <div class="box-left">
            @foreach (var x in Model)
            {


                <div class="bot-img">
                    <img src="@x.BlogImage" alt="" />
                </div>
                <div class="bot-desc">
                    <p>@x.Description.Substring(0,80)...</p>
                </div>
               
                <div class="clear"></div>
            }
        </div>
       
            @Html.Action("Partial5","Default")
        </div>

TravelTrip/Views/Default/Partial5.cshtml
@using TravelTrip.Classes
@model List<Blog>

    <div class="box1-left">
        @foreach (var x in Model)
        {


            <div class="bot-img">
                <img src="@x.BlogImage" alt="" />
            </div>
            <div class="bot-desc1">
                <p>@x.Description.Substring(0,80)...</p>
            </div>



            <div class="clear"></div>
        }
    </div>

TravelTrip/Views/Login/Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>

<head>
    <title> Master login Form Responsive Widget Template  :: w3layouts</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content=" Master  Login Form Widget Tab Form,Login Forms,Sign up Forms,Registration Forms,News letter Forms,Elements" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <link href="~/weblogin/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <link href="//fonts.googleapis.com/css?family=Cormorant+SC:300,400,500,600,700" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
</head>

<body>
    <div class="padding-all">
        <div class="header">
            <h1>Tatil Seyahat Bloğu</h1>
        </div>

        <div class="design-w3l">
            <div class="mail-form-agile">
                @using (Html.BeginForm("Login", "Login", FormMethod.Post))
                {
                    <input type="text" name="User" placeholder="User Name  or  email..." required="" />
                    <input type="password" name="Password" class="padding" placeholder="Password" required="" />
                    <input type="submit" value="login">
                }
            </div>
            <div class="clear"> </div>
        </div>

        <div class="footer">
            <p>© 2020  Master  Login form. All Rights Reserved | Design by  <a href="https://w3layouts.com/">  w3layouts </a></p>
        </div>
    </div>
</body>
</html>

TravelTrip/Views/Shared/_AdminLayout.cshtml
@{
    ViewBag.Title = "_AdminLayout";
    Layout = null;
}
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<!DOCTYPE html>
<html>
-
-
-
<body>
   
    <!-- Sidebar -->
    <div class="w3-sidebar w3-light-grey w3-bar-block" style="width:25%">
        <h3 class="w3-bar-item">Menuler</h3>
        @if (User.Identity.IsAuthenticated)
        {
            <a class="w3-bar-item w3-button">Hoşgeldin, @User.Identity.Name</a>
        }

        <a href="/Admin/Index/" class="w3-bar-item w3-button">Bloglar </a>
        <a href="/Admin/CommentList/" class="w3-bar-item w3-button">Yorumlar</a>
        <a href="/Default/Index/" class="w3-bar-item w3-button">Siteye Git</a>
        <a href="/Login/Logout/" class="w3-bar-item w3-button">Çıkış Yap </a>

    </div>

    <!-- Page Content -->
    <div style="margin-left:25%">

        <div class="w3-container w3-teal">
            <h4>Admin Paneli</h4>
        </div>

    

        <div class="w3-container">
            @RenderBody()
        </div>

    </div>

</body>
</html>